// SPDX-License-Identifier: MIT
// Part of PyBLE (https://pyble.dev) — see /LICENSE.

/// "Signal" color tokens (ADR-0008, design-system.md §1). Everything here is a
/// token — no display copy.
///
/// Two families of color exist:
///   1. The scheme roles — generated by `ColorScheme.fromSeed(kPybleBlue)` for
///      light AND dark (see `pyble_theme.dart`); never hand-overridden.
///   2. The hand-authored semantic sets that M3 does not derive: the
///      connection/run [SignalStateColors] and the code-surface
///      [SignalCodeColors] (console streams + editor chrome). Both ship as
///      `ThemeExtension`s so every surface binds to `Theme.of(context)` and
///      never to `Colors.*` literals (NFR-MAINT-2).
///
/// This file may depend on the neutral `Connection` seam types (`ConnState`,
/// `ConsoleStream`) from `package:pyble/pble/` — those are transport-agnostic
/// domain enums, not `lib/ble` transport types, so the import boundary holds.
library;

import 'package:flutter/material.dart';

import 'package:pyble/pble/pble.dart' show ConnState, ConsoleStream;

/// Brand seed — pyble-blue. The single source both ColorSchemes derive from.
const Color kPybleBlue = Color(0xFF2D5BFF);

/// Connection/run STATE colors (design-system.md §1.3), mapped 1:1 to
/// [ConnState]. Frozen `ThemeExtension`.
///
/// **How the pill uses these (review-corrected):** the state color is a
/// *graphic*, not the label text. It renders as the pill's per-state glyph, its
/// always-on 1 px border, and its tint fill (state color composited at 16 %
/// light / 24 % dark over the host `surfaceContainerHighest`). All three clear
/// the ≥ 3:1 non-text-graphic bar in both brightnesses. The pill *label* uses
/// `colorScheme.onSurface` (≈ 14:1), so text contrast is guaranteed regardless
/// of the state hue — never the low-contrast "state color as text on a same-hue
/// tint" the original draft measured against pure white. Distinguishability for
/// color-vision-deficient users comes from the distinct per-state glyph
/// (§7.6) + the always-present text label, with hue only as reinforcement.
///
/// The exact WCAG ratios are asserted by the theme contrast test (owned by
/// app-test-author, `app/test/theme/`), not by prose.
@immutable
class SignalStateColors extends ThemeExtension<SignalStateColors> {
  const SignalStateColors({
    required this.disconnected,
    required this.connecting,
    required this.ready,
    required this.running,
  });

  /// Off / no board — muted slate. Reads as a prompt (border + bluetooth-off
  /// glyph), never as disabled chrome.
  final Color disconnected;

  /// Transitional — scan / connect / HELLO in progress (ochre-amber). Pulses.
  final Color connecting;

  /// Connected, idle, ready to run (green).
  final Color ready;

  /// A program is executing on the board — live (active blue). Pulses.
  final Color running;

  /// Standard (normal-contrast) light set.
  factory SignalStateColors.light() => const SignalStateColors(
    disconnected: Color(0xFF565E6C),
    connecting: Color(0xFF8A5A00),
    ready: Color(0xFF146C2E),
    running: Color(0xFF1B4FD6),
  );

  /// Standard (normal-contrast) dark set.
  factory SignalStateColors.dark() => const SignalStateColors(
    disconnected: Color(0xFFA8B0BF),
    connecting: Color(0xFFFFB868),
    ready: Color(0xFF7ADB92),
    running: Color(0xFFA9C0FF),
  );

  /// High-contrast light set (paired with a `contrastLevel: 1.0` scheme) —
  /// darker/stronger so the glyph + border read at higher separation.
  factory SignalStateColors.highContrastLight() => const SignalStateColors(
    disconnected: Color(0xFF3C434F),
    connecting: Color(0xFF6B4500),
    ready: Color(0xFF0B5020),
    running: Color(0xFF123FB0),
  );

  /// High-contrast dark set.
  factory SignalStateColors.highContrastDark() => const SignalStateColors(
    disconnected: Color(0xFFC8D0DE),
    connecting: Color(0xFFFFD0A0),
    ready: Color(0xFFA6EEB6),
    running: Color(0xFFCBD9FF),
  );

  /// The state color for [state]. The `error` case (FR-UI-6) is deferred: the
  /// frozen [ConnState] carries no `error` member this milestone, so error is
  /// out of scope until the seam adds it (see design-system.md §1.3).
  Color colorFor(ConnState state) {
    switch (state) {
      case ConnState.disconnected:
        return disconnected;
      case ConnState.connecting:
        return connecting;
      case ConnState.ready:
        return ready;
      case ConnState.running:
        return running;
    }
  }

  /// The [SignalStateColors] installed on the current theme. Non-null: every
  /// `PybleTheme` registers it.
  static SignalStateColors of(BuildContext context) =>
      Theme.of(context).extension<SignalStateColors>()!;

  @override
  SignalStateColors copyWith({
    Color? disconnected,
    Color? connecting,
    Color? ready,
    Color? running,
  }) => SignalStateColors(
    disconnected: disconnected ?? this.disconnected,
    connecting: connecting ?? this.connecting,
    ready: ready ?? this.ready,
    running: running ?? this.running,
  );

  @override
  SignalStateColors lerp(ThemeExtension<SignalStateColors>? other, double t) {
    if (other is! SignalStateColors) return this;
    return SignalStateColors(
      disconnected: Color.lerp(disconnected, other.disconnected, t)!,
      connecting: Color.lerp(connecting, other.connecting, t)!,
      ready: Color.lerp(ready, other.ready, t)!,
      running: Color.lerp(running, other.running, t)!,
    );
  }
}

/// Code-surface colors (design-system.md §1.4): the three console streams
/// (stdout/stderr/system, FR-CONSOLE-2) plus the editor's structural chrome
/// (gutter, active line, selection). Frozen `ThemeExtension` so `lib/console`
/// and `lib/editor` bind to tokens, never literals. Syntax-highlight *palettes*
/// remain deferred to `lib/editor`.
///
/// Most values are derived from the (contrast-aware) scheme so they track the
/// active brightness and any `contrastLevel`; only [stderr] is hand-authored,
/// because M3 guarantees no on-pair for error TEXT over an arbitrary surface.
/// [stderr] is verified ≥ 4.5:1 on the console well (`surfaceContainerLowest`)
/// in both brightnesses by the theme contrast test.
@immutable
class SignalCodeColors extends ThemeExtension<SignalCodeColors> {
  const SignalCodeColors({
    required this.stdout,
    required this.stderr,
    required this.system,
    required this.gutter,
    required this.activeLine,
    required this.selection,
  });

  /// Program standard output — reads as ordinary code text.
  final Color stdout;

  /// Program standard error / tracebacks — the one hand-authored severity color.
  final Color stderr;

  /// Client-synthesized app-side notices (reconnected, etc.) — a quiet tone
  /// distinct from stdout and stderr.
  final Color system;

  /// Line-number / gutter text.
  final Color gutter;

  /// Current-line highlight fill (translucent, composited over the field).
  final Color activeLine;

  /// Text-selection fill (translucent, composited over the field).
  final Color selection;

  /// Derive the code-surface colors from a (possibly high-contrast) scheme.
  factory SignalCodeColors.from(ColorScheme scheme) {
    final bool isDark = scheme.brightness == Brightness.dark;
    return SignalCodeColors(
      stdout: scheme.onSurface,
      stderr: isDark ? const Color(0xFFFFB4AB) : const Color(0xFFB3261E),
      system: scheme.onSurfaceVariant,
      gutter: scheme.onSurfaceVariant,
      activeLine: scheme.primary.withValues(alpha: 0.08),
      selection: scheme.primary.withValues(alpha: 0.24),
    );
  }

  /// The text color for a console [stream].
  Color streamColor(ConsoleStream stream) {
    switch (stream) {
      case ConsoleStream.stdout:
        return stdout;
      case ConsoleStream.stderr:
        return stderr;
      case ConsoleStream.system:
        return system;
    }
  }

  /// The [SignalCodeColors] installed on the current theme. Non-null.
  static SignalCodeColors of(BuildContext context) =>
      Theme.of(context).extension<SignalCodeColors>()!;

  @override
  SignalCodeColors copyWith({
    Color? stdout,
    Color? stderr,
    Color? system,
    Color? gutter,
    Color? activeLine,
    Color? selection,
  }) => SignalCodeColors(
    stdout: stdout ?? this.stdout,
    stderr: stderr ?? this.stderr,
    system: system ?? this.system,
    gutter: gutter ?? this.gutter,
    activeLine: activeLine ?? this.activeLine,
    selection: selection ?? this.selection,
  );

  @override
  SignalCodeColors lerp(ThemeExtension<SignalCodeColors>? other, double t) {
    if (other is! SignalCodeColors) return this;
    return SignalCodeColors(
      stdout: Color.lerp(stdout, other.stdout, t)!,
      stderr: Color.lerp(stderr, other.stderr, t)!,
      system: Color.lerp(system, other.system, t)!,
      gutter: Color.lerp(gutter, other.gutter, t)!,
      activeLine: Color.lerp(activeLine, other.activeLine, t)!,
      selection: Color.lerp(selection, other.selection, t)!,
    );
  }
}
