# SPDX-License-Identifier: MIT
# Part of PyBLE (https://pyble.dev) — see /LICENSE.
#
# Installed as /etc/nginx/sites-available/00-pyble-http.conf.

server {
    listen 80;
    listen [::]:80;
    server_name pyble.dev www.pyble.dev pyble.org www.pyble.org;

    location ^~ /.well-known/acme-challenge/ {
        root /var/lib/letsencrypt;
        default_type "text/plain";
        try_files $uri =404;
    }

    location / {
        return 308 https://pyble.dev$request_uri;
    }
}
